#!/bin/bash

# INSTRUCCIONES DE USO - TOKEN REFRESH IMPLEMENTATION
# ====================================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           DEMOSTRACIÓN: JWT TOKEN REFRESH                     ║"
echo "║              Fase 2 - Segundo Parcial UMG                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 OBJETIVOS DEMOSTRADOS:"
echo "   ✅ Login obtiene Access Token + Refresh Token"
echo "   ✅ Access Token accede a endpoints protegidos"
echo "   ✅ Refresh Token renueva Access Token automáticamente"
echo "   ✅ NewRefresh Token es válido inmediatamente"
echo "   ✅ Logout revoca el Token de refresco"
echo "   ✅ Token revocado no puede reutilizarse"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📋 URLS DISPONIBLES:"
echo ""
echo "  🌐 Frontend (usuario final):"
echo "     http://localhost:3000"
echo ""
echo "  📚 API Swagger (documentación):"
echo "     http://localhost:8080/swagger-ui.html"
echo ""
echo "  🔌 API Base:"
echo "     http://localhost:8080"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🔑 CREDENCIALES DE PRUEBA:"
echo ""
echo "   Admin:"
echo "   ├─ Usuario: admin"
echo "   └─ Contraseña: admin123"
echo ""
echo "   Usuario Estándar:"
echo "   ├─ Usuario: user"
echo "   └─ Contraseña: user123"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
