"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "@/context/AuthContext";
import { Package, KeyRound, User as UserIcon, ArrowRight, ShieldCheck, AlertCircle, Loader2, ChevronLeft, Sparkles } from "lucide-react";

export default function LoginPage() {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [closedForInactivity, setClosedForInactivity] = useState(false);
  const { login } = useAuth(); const router = useRouter();
  useEffect(() => setClosedForInactivity(new URLSearchParams(window.location.search).get("reason") === "inactivity"), []);
  const handleLogin = async (e: React.FormEvent) => { e.preventDefault(); if (!username.trim() || !password.trim()) return setError("Por favor completa todos los campos requeridos."); try { setLoading(true); setError(null); await login(username, password); router.push("/dashboard/products"); } catch (err: any) { setError(err.message || "Usuario o contraseña incorrectos."); } finally { setLoading(false); } };
  const fillCredentials = (name: string, pass: string) => { setUsername(name); setPassword(pass); setError(null); };

  return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-stone-100 px-4 py-10 sm:px-6"><div className="pointer-events-none absolute -left-24 top-10 h-96 w-96 rounded-full bg-brand-200/55 blur-3xl" /><div className="pointer-events-none absolute -bottom-24 -right-24 h-96 w-96 rounded-full bg-jade-200/60 blur-3xl" />
    <div className="relative w-full max-w-md"><Link href="/" className="mb-6 inline-flex items-center gap-1.5 text-xs font-bold text-brand-800 transition hover:text-brand-950"><ChevronLeft className="h-4 w-4" />Volver al catálogo</Link>
      <section className="rounded-[2rem] border border-white bg-white/90 p-7 shadow-2xl shadow-brand-950/10 backdrop-blur-xl sm:p-8"><div className="mb-7 text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-brand-700 to-jade-600 text-white shadow-lg shadow-brand-700/20"><Package className="h-6 w-6" /></div><p className="mb-2 flex items-center justify-center gap-1.5 text-[11px] font-bold uppercase tracking-[0.14em] text-jade-700"><Sparkles className="h-3.5 w-3.5" />Acceso seguro</p><h1 className="text-2xl font-black tracking-tight text-zinc-900">Bienvenido de nuevo</h1><p className="mt-2 text-xs text-stone-500">Ingresa para administrar el inventario de productos.</p></div>
        {closedForInactivity && <div className="mb-4 flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-medium text-amber-900"><AlertCircle className="h-4 w-4 shrink-0" />Sesión cerrada por inactividad</div>}
        <div className="mb-5 rounded-2xl border border-stone-200 bg-stone-50 p-3.5"><span className="mb-2 block text-[11px] font-bold uppercase tracking-wider text-stone-500">Acceso rápido de evaluación</span><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => fillCredentials("admin", "admin123")} className="flex items-center justify-center gap-1.5 rounded-xl border border-jade-200 bg-jade-50 px-3 py-2 text-xs font-bold text-jade-800 transition hover:bg-jade-100"><ShieldCheck className="h-3.5 w-3.5" />Admin</button><button type="button" onClick={() => fillCredentials("user", "user123")} className="flex items-center justify-center gap-1.5 rounded-xl border border-brand-200 bg-brand-50 px-3 py-2 text-xs font-bold text-brand-800 transition hover:bg-brand-100"><UserIcon className="h-3.5 w-3.5" />Usuario</button></div></div>
        {error && <div className="mb-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}
        <form onSubmit={handleLogin} className="space-y-4"><label className="block text-xs font-bold uppercase tracking-wide text-zinc-700">Usuario<div className="relative mt-1.5"><UserIcon className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" /><input type="text" required value={username} onChange={(e) => setUsername(e.target.value)} placeholder="admin o user" className="w-full rounded-xl border border-stone-300 bg-white py-2.5 pl-10 pr-4 text-sm text-zinc-900 placeholder:text-stone-400 transition focus:border-jade-500 focus:outline-none focus:ring-2 focus:ring-jade-200" /></div></label><label className="block text-xs font-bold uppercase tracking-wide text-zinc-700">Contraseña<div className="relative mt-1.5"><KeyRound className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" /><input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" className="w-full rounded-xl border border-stone-300 bg-white py-2.5 pl-10 pr-4 text-sm text-zinc-900 placeholder:text-stone-400 transition focus:border-jade-500 focus:outline-none focus:ring-2 focus:ring-jade-200" /></div></label><button type="submit" disabled={loading} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-brand-700/20 transition hover:bg-brand-800 disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <><span>Entrar al sistema</span><ArrowRight className="h-4 w-4" /></>}</button></form>
      </section>
    </div>
  </div>;
}
