"use client";

import React, { useCallback, useEffect, useState } from "react";
import { Product } from "@/entities/product.entity";
import { ProductService } from "@/services/product.service";
import { useAuth } from "@/context/AuthContext";
import { DataTable } from "@/components/DataTable";
import { ViewProductModal, ProductFormModal, DeleteConfirmModal } from "@/components/ProductModals";
import { Boxes, ShieldCheck, User as UserIcon, RefreshCw, CheckCircle, AlertTriangle, PackageCheck, ArchiveX } from "lucide-react";

export default function ProductsPage() {
  const { isAdmin } = useAuth(); const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const [viewProduct, setViewProduct] = useState<Product | null>(null); const [formProduct, setFormProduct] = useState<Product | null>(null); const [formMode, setFormMode] = useState<"create" | "edit">("create"); const [isFormModalOpen, setIsFormModalOpen] = useState(false); const [deleteProduct, setDeleteProduct] = useState<Product | null>(null);
  const showToast = (message: string, type: "success" | "error" = "success") => { setToast({ message, type }); setTimeout(() => setToast(null), 4000); };
  const loadProducts = useCallback(async () => { try { setLoading(true); setProducts(await ProductService.getAll()); } catch (err: any) { showToast(err.message || "Error al cargar la lista de productos", "error"); } finally { setLoading(false); } }, []);
  useEffect(() => { loadProducts(); }, [loadProducts]);
  const handleFormSubmit = async (data: Partial<Product>) => { if (formMode === "create") { await ProductService.create(data); showToast("¡Producto creado exitosamente!"); } else if (formProduct) { await ProductService.update(formProduct.id, data); showToast("¡Producto actualizado exitosamente!"); } await loadProducts(); };
  const handleConfirmDelete = async () => { if (!deleteProduct) return; await ProductService.delete(deleteProduct.id); showToast(`El producto "${deleteProduct.name}" ha sido eliminado.`); await loadProducts(); };
  const available = products.filter((product) => product.inStock).length; const outOfStock = products.length - available;
  const metrics = [{ label: "Productos registrados", value: products.length, icon: Boxes, tone: "brand" }, { label: "Con disponibilidad", value: available, icon: PackageCheck, tone: "jade" }, { label: "Sin existencias", value: outOfStock, icon: ArchiveX, tone: "amber" }];

  return <div className="mx-auto w-full max-w-7xl space-y-7 p-4 sm:p-8 lg:p-10">
    {toast && <div className={`fixed bottom-5 right-5 z-50 flex items-center gap-2.5 rounded-2xl border px-5 py-3 text-sm font-semibold shadow-xl ${toast.type === "success" ? "border-brand-200 bg-brand-50 text-brand-900" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{toast.type === "success" ? <CheckCircle className="h-5 w-5 text-brand-600" /> : <AlertTriangle className="h-5 w-5 text-rose-600" />}{toast.message}</div>}
    <header className="flex flex-col gap-4 rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between sm:p-7"><div><p className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-jade-700"><Boxes className="h-4 w-4" />Módulo de inventario</p><h1 className="text-3xl font-black tracking-tight text-zinc-900">Gestión de productos</h1><p className="mt-1 text-sm text-stone-600">Consulta, organiza y actualiza el inventario en un solo lugar.</p></div><div className="flex items-center gap-3"><button onClick={loadProducts} disabled={loading} title="Recargar listado" aria-label="Recargar listado" className="rounded-xl border border-stone-200 bg-stone-50 p-2.5 text-stone-600 transition hover:border-brand-200 hover:bg-brand-50 hover:text-brand-700 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin text-brand-600" : ""}`} /></button><div className="flex items-center gap-2 rounded-xl border border-stone-200 bg-stone-50 px-3 py-2 text-xs font-semibold text-zinc-700">{isAdmin ? <ShieldCheck className="h-4 w-4 text-jade-600" /> : <UserIcon className="h-4 w-4 text-brand-600" />}<span className={`rounded-md px-2 py-0.5 text-[10px] font-bold ${isAdmin ? "bg-jade-100 text-jade-800" : "bg-brand-100 text-brand-800"}`}>{isAdmin ? "ADMINISTRADOR" : "USUARIO"}</span></div></div></header>
    <section className="grid gap-4 sm:grid-cols-3">{metrics.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-stone-500">{label}</p><p className="mt-2 text-3xl font-black text-zinc-900">{loading ? "—" : value}</p></div><div className={`rounded-xl p-2.5 ${tone === "brand" ? "bg-brand-50 text-brand-700" : tone === "jade" ? "bg-jade-50 text-jade-700" : "bg-amber-50 text-amber-700"}`}><Icon className="h-5 w-5" /></div></div></article>)}</section>
    <DataTable products={products} isAdmin={isAdmin} onView={setViewProduct} onEdit={(product) => { setFormProduct(product); setFormMode("edit"); setIsFormModalOpen(true); }} onDelete={setDeleteProduct} onCreate={() => { setFormProduct(null); setFormMode("create"); setIsFormModalOpen(true); }} />
    <ViewProductModal product={viewProduct} isOpen={Boolean(viewProduct)} onClose={() => setViewProduct(null)} /><ProductFormModal isOpen={isFormModalOpen} onClose={() => setIsFormModalOpen(false)} onSubmit={handleFormSubmit} product={formProduct} mode={formMode} /><DeleteConfirmModal isOpen={Boolean(deleteProduct)} onClose={() => setDeleteProduct(null)} onConfirm={handleConfirmDelete} productName={deleteProduct?.name || ""} />
  </div>;
}
